<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

1. lists
2. numpy arrays
3. dicts
4. tuples
5. dataframes: in the Data Processing basket in Applications part
6. classes: in the Nice chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [92]:
#python lists
py_list = ["apple", "orange", "mango"]
print(py_list)
print(py_list[0])

['apple', 'orange', 'mango']
apple


In [93]:
import numpy

#numpy arrays - must put a bracket outside the sq brackets
np_list = numpy.array(["apple", "orange", "mango"])
print(np_list)
print(np_list[1])

['apple' 'orange' 'mango']
orange


In [94]:
#dictionaries: use {
dict = {
    "red": "apple",
    "orange": "orange",
    "yellow": "mango"
}
print(dict)
print(dict["yellow"])

{'red': 'apple', 'orange': 'orange', 'yellow': 'mango'}
mango


## 1.2 Accessing data from a list (or array)

using [], starts from 0

### Reverse indexing: -1

In [95]:
np_list = numpy.array(["apple", "orange", "mango"])
print(np_list)
print(np_list[-1])

['apple' 'orange' 'mango']
mango


## 1.3 Accessing data from a dictionary: printing the key to get the value

In [96]:
dict = {
    "red": "apple",
    "orange": "orange",
    "yellow": "mango"
}
print(dict)
print(dict["yellow"])

{'red': 'apple', 'orange': 'orange', 'yellow': 'mango'}
mango


### accessing all the keys and values using .keys() or .values()

In [97]:
dict = {
    "red": "apple",
    "orange": "orange",
    "yellow": "mango"
}

print(dict.keys())
print(dict.values())

dict_keys(['red', 'orange', 'yellow'])
dict_values(['apple', 'orange', 'mango'])


## 1.4 Higher dimensional lists - 2D lists are known as arrays

- dictionary can store things tgt like real and corresponding superhero names (or colour and fruits)
- for lists, 2 are needed
- a workaround is to use 2D lists with [] inside a bigger []

In [98]:
array = [["red","apple"], ["orange", "orange"], ["yellow", "mango"]]
print(array[1])
len(array)

['orange', 'orange']


3

# 2 Lists vs. Arrays. NOTE: can use the python 2d list (named as array) to create a new numpy array by just creating nparray = numpy.array(listname)**

some similarities but more differences

## 2.1 Size eg len() and SHAPE - 2d

- both can use len()
**can use the python 2d list (named as array) to create a new numpy array by just creating nparray = numpy.array(listname)**

In [99]:
import numpy
print(len(array))
nparray = numpy.array(array)
print(len(nparray))

#shape is a property of numpy arrays
print(nparray.shape)

3
3
(3, 2)


## 2.2 Arrays are fussy about type - only 1 type per array (int or float or str). lists more relaxed. be mindful when having datasets w both numbers and text

In [100]:
newlist = [2, 10, "A"]
newarray = numpy.array(newlist)
print(newlist)
print(newarray)
print(newlist[0] + newlist[1]) #testing whether the numerical values can be added tgt. ans: yes
print(newarray[0] + newarray[1]) #they are added as strings, "2" + "10" = "210"
print(int(newarray[0]) + int(newarray[1])) #switching back to int and adding. it works.

[2, 10, 'A']
['2' '10' 'A']
12
210
12


## 2.3 Adding a number

In [101]:
#using the above list and array
print(newlist[0] + 10)
print(int(newarray[0]) + 10)
#printing the newarray[0] + 10 returns an error.

12
12


In [102]:
print(newarray[0] + 10) #will not workk

TypeError: can only concatenate str (not "int") to str

## 2.4 Adding another list. adding lists adds elements, adding arrays does operations

In [103]:
mathlist1 = [10, 20, 30, 40, 50]
mathlist2 = [1, 2, 3, 4, 5]
matharray1 = numpy.array(mathlist1)
matharray2 = numpy.array(mathlist2)

print(mathlist1 + mathlist2)
print(matharray1 + matharray2)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]
[11 22 33 44 55]


## 2.5 Multiplying by a Number - same thing. multiplying lists adds elements, multiplying arrays does operations.

In [104]:
print(mathlist1*2)
print(matharray1*2)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 20  40  60  80 100]


In [105]:
#multiplying lists by lists does not work
print(mathlist1 * mathlist2)

TypeError: can't multiply sequence by non-int of type 'list'

In [106]:
#but multiplying arrays by arrays works!!!!
print(matharray1 * matharray2)

[ 10  40  90 160 250]


## 2.6 Squaring

In [107]:
print(mathlist2 ** mathlist1) #will not workk

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'

In [108]:
print(matharray1 ** matharray2)

[       10       400     27000   2560000 312500000]


## 2.7 Asking questions eg. do these values in an array, 1 by 1, satisfy a condition?

In [109]:
print(matharray1 == 10)
print(matharray1 > 10)

[ True False False False False]
[False  True  True  True  True]


In [110]:
#no work for lists
print(mathlist1 == 10)
print(mathlist1 > 10)

False


TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics using sum(), min(), max()

In [111]:
print(min(matharray1))
print(max(matharray1))
print(min(mathlist1))
print(max(mathlist1))

#for lists, put the max() functions at the front. for arrays, an alternative way is to type arrayname.max() but both works. the .max() for lists will not work
print(max(matharray1))
print(matharray1.max())
print(sum(matharray1))
print(sum(mathlist1))
print(matharray1.sum())

10
50
10
50
50
50
150
150
150


In [112]:
print(mathlist1.sum())  #this format only works for arrays

AttributeError: 'list' object has no attribute 'sum'

# Exercises & Self-Assessment

In [116]:
# an operation on a list works on the whole list. an operation on an array works on the individual elements of the array.

lista = [1, 2, 3, 4, 5]
listb = [6, 7, 8, 9, 10, 11]
#trying out diff sizes of lists and arrays
arra = numpy.array(lista)
arrb = numpy.array(listb)
print(lista + listb) #works, just adds on
print(arra + arrb) #error message!!!

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## Footnotes