<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

- prev chapter (storing data, need): lists, arrays, dicts
- this chapter: **accessing and modifying structures** bc these things are v impt

# 1 Subsetting: Indexing and Slicing

- **subsetting**: select a subset of data in list/array
- **indexing**: a form of subsetting, where *single element is picked*
- **slicing**: selecting a *range of elements*

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
newlist = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
import numpy
newarray = numpy.array(newlist)
print(newarray)

['a1' 'b2' 'c3' 'd4' 'e5' 'f6' 'g7' 'h8' 'i9' 'j10']


In [5]:
#indexing!
x = newarray
print(x[0])
print(x[-1]) #last element
print(x[1:3]) #2nd to 3rd element, NUMBER ON RIGHT IS NOT INCLUDING

#NOTE: the final number eg. [1:3] ends at index 2, does not include 3.
# so [1:3] only includes index 1, 2 which is the 2nd and 3rd item on the list

a1
j10
['b2' 'c3']


In [6]:
#increments of 2 (alternate)
print(x[1:6:2]) #1st to 5th index meaning 2nd to 6th thing on the list, alternating

['b2' 'd4' 'f6']


In [16]:
#from start to somewhere in the middle:
print(x[:6]) #does NOT include 6th pos (ie. 7th element)

#from somewhere in the middle to end:
print(x[6:]) #starts from 6th pos (ie. 7th element)

#indexing in reverse
print(x[6:0:-1])
#note: must list from right to left, otherwise output is []
print(x[0:6:-1]) #output is []

#reversing the whole list
print(x[::-1])

['a1' 'b2' 'c3' 'd4' 'e5' 'f6']
['g7' 'h8' 'i9' 'j10']
['g7' 'f6' 'e5' 'd4' 'c3' 'b2']
[]
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


## 1.2 Arrays only, NOT FOR LISTS | Subsetting by masking. gives T/F

In [23]:
y = numpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(y)
mask = y > 3 #this sets the masking condition, output is T/F
print(mask)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False  True  True  True  True  True  True  True]


In [22]:
#asking numpy which of the values give out TRUE:
y[mask] #square brackets!!!

array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
#shortcut for masking
y[y > 3] #this works because the mask is just an equation/inequality

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
#inverting masks, asking for FALSE: using ~ with round brackets inside. the ~ is called Bitwise Not operator
y[~(y>3)]

array([1, 2, 3])

In [36]:
#combining conditions. brackets are impt
#AND only for elements which exist that fit both, other will return empty
print(y[(y < 2) & (y > 8)]) #returns empty
print(y[(y > 4) & (y < 9)])
#OR for either or. use "|" for OR
print(y[(y > 4) | (y < 9)]) #this prints all elements without repeating
print(y[(y < 2) | (y > 8)])

[]
[5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  9 10]


## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [40]:
list2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"], [5, "E"], [6, "F"], [7, "G"], [8, "H"], [9, "I"], [10, "J"]]
print(list2d)
print(list2d[3]) #index 3, pos 4

#isolating 1 item from a 2D list, using another sq bracket
print(list2d[3][0])
print(list2d[3][1])

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]
[4, 'D']
4
D


In [41]:
#if using arrays, isolating 1 item from array will use 1 pair of sq brackets
array = numpy.array(list2d)
print(array[4])
print(array[4,0])

['5' 'E']
5


In [48]:
print(array[4][0]) #the method for lists works for arrays too BUT for 2.3.1 (splitting into ranges then separating elements) use 1 sq bracket

5


In [45]:
print(list2d[:3]) #index 0 to 2, means pos 1-3
print(array[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


### splitting 2d lists and arrays into ranges and then separate elements eg. [:3][0]

In [51]:
#arrays no issue, use single brackets
print(array[:3,0]) #use single bracket!!
print(array[:3][0])
print(list2d[:3][0])

['1' '2' '3']
['1' 'A']
[1, 'A']


In [63]:
#another example
print(array[3:6,0])
print(array[3:6][0])
print(list2d[3:6][0])
#print everything? use :
print(array[:, 0]) #everything but 1st element
print(array[:,1])
print(array[:,-1]) #reverse indexing
print(array[::-1]) #whole array but in reverse
print(array[::-1,0]) #whole array, only numbers but in reverse

['4' '5' '6']
['4' 'D']
[4, 'D']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
[['10' 'J']
 ['9' 'I']
 ['8' 'H']
 ['7' 'G']
 ['6' 'F']
 ['5' 'E']
 ['4' 'D']
 ['3' 'C']
 ['2' 'B']
 ['1' 'A']]
['10' '9' '8' '7' '6' '5' '4' '3' '2' '1']


## 1.4 Growing lists

- pros of arrays: slicing syntax more intuitive, can carry out operations
- cons: will have issues changing size of numpy array

- pros of lists: ease and efficiency in growing

In [68]:
#multiplying lists will add on
x = [1,2]*5
print(x)

y= numpy.array([1,2])*5
print(y)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
[ 5 10]


In [72]:
#THREE WAYS to grow a list by appending 1 element at a time
#1: +
x = [1]
x = x +[2]
x = x +[3]
x = x+[4]
print(x)

#2: +=
x2 = [1]
x2 += [2]
x2 += [3]
x2 += [4]
print(x2)

#3: .append #this oone runs ~1.5 faster than the rest
x3 = [1]
x3.append(2)
x3.append(3)
x3.append(4)
print(x3)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


### append vs extend - append may add a list inside a list instead of extending

In [74]:
x = [1, 2, 3]
x += [4, 5, 6] #this EXTENDS
print(x)

x2 = [1, 2, 3]
x2.append([4, 5, 6])
print(x2)

x3 = [1, 2, 3]
x3.extend([4, 5, 6])
print(x3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]
[1, 2, 3, 4, 5, 6]


# Some loose ends
- tuples are immutable, cannot be changed after creation

## 1.5 Tuples use round brackets

In [76]:
t = (1, 2, 3)
print(t[1])
#can access data but cannot change data
t.extend([4, 5, 6])

2


AttributeError: 'tuple' object has no attribute 'extend'

In [79]:
#testing changing data in a list
l = [1, 2, 3]
print(l[1])
l[1] = 6
print(l)

2
[1, 6, 3]


In [80]:
t = (1, 2, 3)
print(t[1])
#can access data but cannot change data
t[1] = -1
print(t)

2


TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [82]:
#tldr when copying do not x = y = z, make copies by y = x.copy()
#has to do with immutable and mutable objects
x = l.copy()
y = l.copy()
print(l, x, y)

[1, 6, 3] [1, 6, 3] [1, 6, 3]


# Exercises & Self-Assessment

In [83]:
#is it necessary to write something here if i've tried out most of the exercises mentioned here?

## Footnotes